steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'cf_deploy'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: 'piper'
      space: 'infra-testing'
